<?php

use PHPUnit\Framework\TestCase;
use LEADGEN\Hooks\Shortcode;
use Brain\Monkey;

class ShortcodeTest extends TestCase {
	private $template;

	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		Monkey\setUp();
		$this->template = $this->createMock( \LEADGEN\Templates\Shortcode_Template::class );
	}

	public function test_register() {
		$subject = new Shortcode( $this->template );
		$subject->register();
		self::assertTrue( has_action( 'init', [ $subject, 'define' ] ) );
	}

	protected function tearDown(): void {
		Monkey\tearDown();
		parent::tearDown();
	}

}
